module.exports = [
  {
    id: 1,
    observedDate: '2019-01-01',
    nameEn: 'New Year’s Day',
    nameFr: 'Jour de l’An',
    federal: 1,
    provinces: [
      { id: 'AB', nameEn: 'Alberta', nameFr: 'Alberta' },
      { id: 'BC', nameEn: 'British Columbia', nameFr: 'Colombie-Britannique' },
      { id: 'MB', nameEn: 'Manitoba', nameFr: 'Manitoba' },
      { id: 'NB', nameEn: 'New Brunswick', nameFr: 'Nouveau-Brunswick' },
      { id: 'NL', nameEn: 'Newfoundland and Labrador', nameFr: 'Terre-Neuve-et-Labrador' },
      { id: 'NT', nameEn: 'Northwest Territories', nameFr: 'Territoires du Nord-Ouest' },
      { id: 'NS', nameEn: 'Nova Scotia', nameFr: 'Nouvelle-Écosse' },
      { id: 'NU', nameEn: 'Nunavut', nameFr: 'Nunavut' },
      { id: 'ON', nameEn: 'Ontario', nameFr: 'Ontario' },
      { id: 'PE', nameEn: 'Prince Edward Island', nameFr: 'Île-du-Prince-Édouard' },
      { id: 'QC', nameEn: 'Quebec', nameFr: 'Québec' },
      { id: 'SK', nameEn: 'Saskatchewan', nameFr: 'Saskatchewan' },
      { id: 'YT', nameEn: 'Yukon', nameFr: 'Yukon' },
    ],
  },
  {
    id: 2,
    observedDate: '2019-02-18',
    nameEn: 'Louis Riel Day',
    nameFr: 'Journée Louis Riel',
    federal: 0,
    provinces: [{ id: 'MB', nameEn: 'Manitoba', nameFr: 'Manitoba' }],
  },
  {
    id: 3,
    observedDate: '2019-02-18',
    nameEn: 'Islander Day',
    nameFr: 'Fête des Insulaires',
    federal: 0,
    provinces: [{ id: 'PE', nameEn: 'Prince Edward Island', nameFr: 'Île-du-Prince-Édouard' }],
  },
  {
    id: 4,
    observedDate: '2019-02-18',
    nameEn: 'Family Day',
    nameFr: 'Fête de la famille',
    federal: 0,
    provinces: [
      { id: 'AB', nameEn: 'Alberta', nameFr: 'Alberta' },
      { id: 'BC', nameEn: 'British Columbia', nameFr: 'Colombie-Britannique' },
      { id: 'NB', nameEn: 'New Brunswick', nameFr: 'Nouveau-Brunswick' },
      { id: 'ON', nameEn: 'Ontario', nameFr: 'Ontario' },
      { id: 'SK', nameEn: 'Saskatchewan', nameFr: 'Saskatchewan' },
    ],
  },
  {
    id: 5,
    observedDate: '2019-02-18',
    nameEn: 'Heritage Day',
    nameFr: 'Fête du Patrimoine',
    federal: 0,
    provinces: [{ id: 'NS', nameEn: 'Nova Scotia', nameFr: 'Nouvelle-Écosse' }],
  },
  {
    id: 6,
    observedDate: '2019-03-17',
    nameEn: 'Saint Patrick’s Day',
    nameFr: 'Jour de la Saint-Patrick',
    federal: 0,
    provinces: [
      { id: 'NL', nameEn: 'Newfoundland and Labrador', nameFr: 'Terre-Neuve-et-Labrador' },
    ],
  },
]
