name: Build and Deploy Node.js App to Cloud Run

on:
  push:
    branches:
      - main
      - update-workflow

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: us-east1
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Configure auth with Service Account with permissions to build and deploy on Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      # Docker auth and build
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          registry: 'gcr.io'
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Build and Push Container
        run: |-
          docker buildx build --platform linux/amd64 -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} --build-arg GITHUB_SHA_ARG=${{ github.sha }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.RUN_REGION }}
